apiVersion: v1
kind: Service
metadata:
  name: flaskweb-app-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30124
  selector:
    app: flaskweb-app
    tier: backend
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
 name: flaskweb-app-microservice
 labels:
  app: flaskweb-app
  tier: backend
spec:
 replicas: 3
 selector:
  matchLabels:
    tier: backend
  matchExpressions:
    - {key: tier, operator: In, values: [backend]}
 template:
  metadata:
   labels:
    app: flaskweb-app
    tier: backend
  spec:
   containers:
   - name: flaskweb-app
     image: douglasdb/flaskweb-app
     ports:
     - containerPort: 5000
