apiVersion: v1
kind: Service
metadata:
  name: quotes-mongosed-service
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  ports:
  - port: 10254
    targetPort: 10254
  selector:
    app: quotes-mongosed
    tier: backend
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
 name: quotes-mongosed-rs
 labels:
  app: quotes-mongosed
  tier: backend
spec:
 replicas: 2
 selector:
  matchLabels:
    tier: backend
  matchExpressions:
    - {key: tier, operator: In, values: [backend]}
 template:
  metadata:
   labels:
    app: quotes-mongosed
    tier: backend
  spec:
   containers:
   - name: quotes-mongosed
     env:
     - name: SERVER_HOST
       value: 172.17.0.3
     image: douglasdb/quotes-mongosed
     ports:
     - containerPort: 10254
