apiVersion: v1
kind: Service
metadata:
  name: quotes-mongosed-service
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  ports:
  - port: 10254
    targetPort: 10254
  selector:
    app: quotes-mongosed
    tier: backend
---
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-01-01T21:07:13Z'
  name: quotes-mongosed-service
  namespace: myproject
  resourceVersion: '5228'
  selfLink: /oapi/v1/namespaces/myproject/routes/quotes-mongosed-service
  uid: 363e3a63-0e09-11e9-988d-00155d139409
spec:
  host: quotes-mongosed-service-myproject.10.0.75.2.nip.io
  to:
    kind: Service
    name: quotes-mongosed-service
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-01-01T21:07:13Z'
          status: 'True'
          type: Admitted
      host: quotes-mongosed-service-myproject.10.0.75.2.nip.io
      routerName: router
      wildcardPolicy: None
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
 name: quotes-mongosed-rs
 labels:
  app: quotes-mongosed
  tier: backend
spec:
 replicas: 2
 selector:
  matchLabels:
    tier: backend
  matchExpressions:
    - {key: tier, operator: In, values: [backend]}
 template:
  metadata:
   labels:
    app: quotes-mongosed
    tier: backend
  spec:
   containers:
   - name: quotes-mongosed
     env:
     - name: SERVER_HOST
       value: 172.17.0.2
     image: douglasdb/quotes-mongosed
     ports:
     - containerPort: 10254
